Script to obtain diagonals of arrays, including rectangular arrays.

In [1]:
import numpy as np

In [2]:
np.random.seed(536)

In [3]:
test_wide = np.random.randint(0, 10, (4,10))
test_long = np.random.randint(0, 10, (10,4))

In [4]:
test_wide

array([[5, 2, 3, 5, 5, 1, 5, 9, 4, 0],
       [9, 1, 4, 0, 6, 1, 4, 5, 0, 9],
       [9, 7, 2, 1, 0, 8, 8, 0, 3, 4],
       [6, 9, 0, 3, 7, 1, 5, 8, 8, 3]])

In [5]:
test_long

array([[4, 5, 0, 5],
       [0, 8, 2, 2],
       [4, 5, 7, 6],
       [3, 4, 4, 1],
       [1, 6, 8, 6],
       [2, 5, 4, 6],
       [1, 5, 3, 8],
       [8, 5, 4, 6],
       [9, 0, 5, 4],
       [4, 3, 1, 2]])

In [6]:
np.diag(test_long, 1) # compare with numpy's inbuilt function

array([5, 2, 6])

In [7]:
test_wide[[0,3], [5,6]]

array([1, 5])

In [11]:
def get_diag(arr, k=0, from_element=None):
    '''from element = coordinates of an array element,
        use if want to calculate the offset from coords
        instead of giving the offset itself'''
    N,M = arr.shape
    if from_element != None:
        k = from_element[1] - from_element[0] # same as numpy
    if k > 0:
        row_lim = min(N, M-k)
        possible_rows = np.arange(0, row_lim)
        col_lim = min(M, k+N)
        possible_cols = np.arange(k, col_lim)
    elif k =< 0:
        row_lim = min(N, -k+M)
        possible_rows = np.arange(-k, row_lim)
        col_lim = min(M, N-(-k))
        possible_cols = np.arange(0, col_lim)
    return(arr[possible_rows, possible_cols])

In [26]:
get_diag(test_long, k=0)

array([4, 8, 7, 1])

In [27]:
get_diag(test_long, k=-7)

array([8, 0, 1])

In [30]:
get_diag(test_wide, k=7)

array([9, 0, 4])